---
# Mongo Version: 2.7.6, 3.5, 4.2

version: '3'
services:
  mongo:
    image: mongo:3.5
    container_name: mongo-server
    volumes:
      - /etc/localtime:/etc/localtime
      - ${XDC_MONGO_DATA:-./data}:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017
